[package]
name = "stilla"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ammonia = "3.2.1"
clap = { version = "4.0.10", features = ["derive"] }
comrak = "0.14.0"
tera = "1.17.1"
walkdir = "2.3.2"
